nodeLinker: node-modules
npmAuthToken: "${NODE_AUTH_TOKEN}"

logFilters:
  - code: YN0060
    text: "eslint-plugin-import"
    level: discard
  - code: YN0086
    level: discard
  - code: YN0069
    text: "eslint-plugin-import"
    level: discard
