/**
 * Main configuration interface for Pyroscope profiling.
 *
 * Uses plain TypeScript interfaces (not Joi validation) to configure the Pyroscope client
 * and profiling behavior.
 *
 * @example
 * ```typescript
 * const config: IPyroscopeConfig = {
 *   enabled: true,
 *   serverAddress: 'http://localhost:4040',
 *   applicationName: 'my-service',
 *   environment: 'production',
 *   version: '1.0.0',
 *   tags: { region: 'us-east-1' },
 *   basicAuthUser: process.env.PYROSCOPE_USER,
 *   basicAuthPassword: process.env.PYROSCOPE_PASSWORD,
 * };
 * ```
 */
export interface IPyroscopeConfig {
	/** Whether profiling is active. When `false`, all profiling calls are no-ops. */
	enabled: boolean;
	/** URL of the Pyroscope server (e.g. `'http://localhost:4040'`). Must start with `http://` or `https://`. */
	serverAddress: string;
	/** Application identifier shown in the Pyroscope UI. */
	applicationName: string;
	/** Environment label (e.g. `'production'`, `'staging'`). Attached as a tag when provided. */
	environment?: string;
	/** Application version string. Attached as a tag when provided. */
	version?: string;
	/** Sampling rate between 0 and 1. Values outside this range are rejected by `ProfilingConfigValidator.Validate()`. */
	sampleRate?: number;
	/** Profile types to collect. Defaults to CPU profiling if not specified. */
	profileTypes?: TProfileType[];
	/** Global key-value tags applied to all profiles. Note: `@pyroscope/nodejs` does not support dynamic tag changes after initialization. */
	tags?: Record<string, string>;
	/** Basic auth username for the Pyroscope server. Must be paired with `basicAuthPassword`. */
	basicAuthUser?: string;
	/** Basic auth password for the Pyroscope server. Must be paired with `basicAuthUser`. */
	basicAuthPassword?: string;
	/** Enable TLS for the Pyroscope server connection. */
	tlsEnabled?: boolean;
	/** Path to the TLS certificate file. */
	tlsCertPath?: string;
	/** Path to the TLS private key file. */
	tlsKeyPath?: string;
	/** Path to the TLS CA certificate file. */
	tlsCaPath?: string;
	/** Skip TLS certificate verification. Unsafe — use only in development environments. */
	tlsInsecureSkipVerify?: boolean;
	/** Log level for internal Pyroscope client logging. */
	logLevel?: 'debug' | 'info' | 'warn' | 'error';
	/** Whether to register the built-in `/profiling/*` health endpoints. Defaults to `true`. */
	enableHealthChecks?: boolean;
	/** Active-profile count above which the health indicator returns degraded status. Defaults to 1000. */
	degradedActiveProfilesThreshold?: number;
	/** Base delay in milliseconds for exponential backoff on retries. Defaults to 100. */
	retryBaseDelayMs?: number;
	/** Maximum delay in milliseconds between retries. Defaults to 10000. */
	retryMaxDelayMs?: number;
	/** Random jitter in milliseconds added to retry delays. Defaults to 1000. */
	retryJitterMs?: number;
	/** Maximum length for tag values. Values exceeding this are truncated. Defaults to 200. */
	tagMaxLength?: number;
}

/**
 * Type of profiling to collect.
 *
 * - 'cpu': CPU time profiling
 * - 'memory': Memory allocation profiling
 * - 'goroutine': Goroutine profiling (Go compatibility)
 * - 'mutex': Mutex contention profiling (Go compatibility)
 * - 'block': Block contention profiling (Go compatibility)
 */
export type TProfileType = 'cpu' | 'memory' | 'goroutine' | 'mutex' | 'block';

/**
 * Profiling metrics collected for a single operation.
 *
 * Contains timing and resource usage information from a profiling session.
 */
export interface IProfileMetrics {
	/** CPU time consumed during the profiling session, in milliseconds. */
	cpuTime: number;
	/** Memory allocated during the profiling session, in bytes. */
	memoryUsage: number;
	/** Total wall-clock duration of the profiling session, in milliseconds. */
	duration: number;
	/** Unix timestamp (milliseconds) when the metrics were recorded. */
	timestamp: number;
	/** Optional metadata tags attached to the profiling session. */
	tags?: Record<string, string>;
}

/**
 * Profiling context for a single operation.
 *
 * Represents the lifecycle of a profiling session, from start to stop.
 * Used internally by PyroscopeService and decorators/interceptors.
 */
export interface IProfileContext {
	/** Unique identifier generated by `PyroscopeService.StartProfiling()`. Set automatically; do not supply manually. */
	profileId?: string;
	/** Name of the function or operation being profiled. Used as the profile label in Pyroscope. */
	functionName: string;
	/** Name of the class containing the method, if applicable. */
	className?: string;
	/** Name of the method being profiled, if applicable. */
	methodName?: string;
	/** Unix timestamp (milliseconds) when profiling started. Set automatically if not provided. */
	startTime?: number;
	/** Unix timestamp (milliseconds) when profiling ended. Set by `StopProfiling()`. */
	endTime?: number;
	/** Computed duration in milliseconds (`endTime - startTime`). Set by `StopProfiling()`. */
	duration?: number;
	/** Error thrown during the profiled operation, if any. */
	error?: Error;
	/** Metadata tags attached to this profiling session. */
	tags?: Record<string, string>;
}
