/** @packageDocumentation */

// ============================================================================
// Metrics Exporter Interfaces
// ============================================================================
export type { IMetricsExporter, MetricDescriptor, MetricValue, MetricType } from './common/interfaces/metrics-exporter.interface.js';
export { InstrumentationRegistry } from './common/registry/instrumentation-registry.js';

// ============================================================================
// Common Module Exports
// ============================================================================
export {
	GlobalExceptionFilter,
	HttpExceptionFilter,
	LoggingInterceptor,
	HTTPMetricsInterceptor,
	BaseValidationPipe,
	ValidationPipe,
	RequestProperty,
	getNestedProperty,
	getRequestFromContext,
	createRequestPropertyDecorator,
	createConditionalDecorator,
	createValidatingDecorator,
	createTransformingDecorator,
	BaseDecoratorOptions,
	ConditionalDecoratorOptions,
	ValidatingDecoratorOptions,
	TransformingDecoratorOptions,
	Query,
	Params,
	Body,
	Headers,
	Cookies,
	LogContext,
	GRAFANA_TIMEOUT,
	LOKI_TIMEOUT,
	PROMETHEUS_TIMEOUT,
	HTTP_CLIENT_TIMEOUT,
	CONFIG_VALIDATION_TIMEOUT,
	LogEntry,
	LogLevel,
	LogMetadata,
	LOG_LEVEL_STRINGS,
	ILogger,
	IContextualLogger,
	AppLogger,
	NestLoggerAdapter,
	AuditLoggerService,
	ErrorSanitizerService,
	ErrorCategorizerService,
	HttpClientService,
	CSRFService,
	MetricsRegistryService,
	HealthCheckService,
	HealthStatus,
	BaseMetricsCollector,
	MetricsController,
	CSRFGuard,
	MetricsGuard,
	CommonModule,
	MetricsModule,
	SharedThrottlerModule,
	type SharedThrottlerConfig,
	BaseApplicationError,
	createError,
	ERROR_CONFIGS,
	ErrorConfig,
	ErrorType,
	BadRequestError as CommonBadRequestError,
	UnauthorizedError as CommonUnauthorizedError,
	ForbiddenError as CommonForbiddenError,
	NotFoundError as CommonNotFoundError,
	ConflictError as CommonConflictError,
	UnprocessableEntityError as CommonUnprocessableEntityError,
	InternalServerError as CommonInternalServerError,
	BadGatewayError as CommonBadGatewayError,
	ServiceUnavailableError as CommonServiceUnavailableError,
	GatewayTimeoutError as CommonGatewayTimeoutError,
	ApplySecurityMiddleware,
	SecurityBootstrapOptions,
	CreateRateLimitConfig,
	RateLimitConfig,
	RateLimitDescriptor,
	LazyGetter,
	OptionalLazyGetter,
	TokenLazyGetter,
	LazyModuleRefService,
	LazyGetterDependencies,
	OptionalGetterConfig,
	CreateMemoizedLazyGetter as createMemoizedLazyGetter,
	CreateOptionalLazyGetter as createOptionalLazyGetter,
	IsLazyModuleRefService as isLazyModuleRefService,
	LazyGetterNamingConventions,
	type IHealthCheck,
	getErrorStack,
	getErrorMessage,
	AsyncModuleOptions,
	createAsyncOptionsProvider,
	createAsyncProviders,
} from './common/index.js';

// ============================================================================
// Config Module Exports
// ============================================================================
export {
	ConfigService,
	ValidationService,
	ConfigModule,
	AppConfig,
	DatabaseConfig,
	CacheConfig as ConfigCacheConfig,
	AuthConfig,
	ValidationResult,
	ConfigSchema,
	EnvironmentOptions,
	CreateValidationSchema,
	ValidateConfig,
	CreateStringSchema,
	CreateNumberSchema,
	CreateBooleanSchema,
	CreateUriSchema,
	CreatePortSchema,
	CreateEnvironmentSchema,
	CreateJwtExpirationSchema,
} from './config/index.js';

// ============================================================================
// Guards Exports
// ============================================================================
export { CustomThrottleGuard } from './guards/index.js';
