name: CI

on:
  push:
    branches: [main]
    tags-ignore: ['v*']
  pull_request:
    branches: [main]
  workflow_call:

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    env:
      CI: true
      NX_DAEMON: false
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Pipeline
        run: yarn pipeline
